---
title: "Assignment 4"
output: html_document
date: "2023-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = F,
                      message = F)
```


```{r load_packages}
library(tidyverse)
library(caret)
library(ggbiplot)
library(stats)
library(factoextra)
library(cluster)
```

## Part I: Implementing a Simple Prediction Pipeline

The New York City Department of Health administered a questionnaire on general health and physical activity among residents. 

```{r load_data}
PAT_df = readr::read_csv("./class4_p1.csv") %>% 
  dplyr::rename(id = `...1`,
                htn = chronic1,
                diabetes = chronic3,
                asthma = chronic4,
                tobacco = tobacco1,
                alcohol = alcohol1,
                pa_min = gpaq8totmin,
                walk_days = gpaq11days,
                physical_act = habits5,
                diet = habits7,
                gender = dem3,
                hisp_lat = dem4,
                us_born = dem8) %>% 
  mutate_at(vars(htn:asthma, tobacco:alcohol, physical_act:povertygroup), ~ as.factor(.)) 

summary(PAT_df) %>% knitr::kable()
```

```{r partition_data}
set.seed(123)

#Drop category and ID variable and remove missings
PAT_df = PAT_df %>% 
  select(-id) %>% 
  na.omit()

#Finding correlated predictors
PAT_numeric = PAT_df %>% dplyr::select(where(is.numeric))
correlations = cor(PAT_numeric, use="complete.obs")
high_correlations = findCorrelation(correlations, cutoff=0.4)

#Remove highly correlated features
new.data.low.corr = PAT_numeric[,-high_correlations]

#Centering and Scaling
set.up.preprocess = preProcess(PAT_numeric, method=c("center", "scale"))

#Output pre-processed values
transformed.vals = predict(set.up.preprocess, PAT_numeric)

#Creating balanced partitions in the data
train.index = createDataPartition(PAT_df$healthydays, p = 0.7, list = FALSE)

hcvdat.train = PAT_df[train.index,]
hcvdat.test = PAT_df[-train.index,]

summary(hcvdat.test)
summary(hcvdat.train)

```


## Part II: Conducting an Unsupervised Analysis

